schema_version_key: SCHEMAS.CONFIG_SCHEMA_VERSION
suites:
  - suite_id: IDS.SUITE_IDS.SUITE_SYNTH_V1
    seed_key: SEEDS.SEED_SYNTH_SUITE
    experiment_ids:
      - IDS.EXPERIMENT_IDS.EXP_SYNTH_SANITY_V1
      - IDS.EXPERIMENT_IDS.EXP_SYNTH_REDUNDANCY_SWEEP_V1
  - suite_id: IDS.SUITE_IDS.SUITE_REAL_IOI_V1
    seed_key: SEEDS.SEED_REAL_SUITE
    experiment_ids:
      - IDS.EXPERIMENT_IDS.EXP_REAL_IOI_V1
      - IDS.EXPERIMENT_IDS.EXP_REAL_IOI_OOD_V1
  - suite_id: IDS.SUITE_IDS.SUITE_REAL_GREATERTHAN_V1
    seed_key: SEEDS.SEED_REAL_SUITE
    experiment_ids:
      - IDS.EXPERIMENT_IDS.EXP_REAL_GREATERTHAN_V1
      - IDS.EXPERIMENT_IDS.EXP_REAL_GREATERTHAN_OOD_V1
  - suite_id: IDS.SUITE_IDS.SUITE_REAL_GREATERTHAN_YN_V1
    seed_key: SEEDS.SEED_REAL_SUITE
    experiment_ids:
      - IDS.EXPERIMENT_IDS.EXP_REAL_GREATERTHAN_YN_V1
      - IDS.EXPERIMENT_IDS.EXP_REAL_GREATERTHAN_YN_OOD_V1
  - suite_id: IDS.SUITE_IDS.SUITE_REAL_INDUCTION_V1
    seed_key: SEEDS.SEED_REAL_SUITE
    experiment_ids:
      - IDS.EXPERIMENT_IDS.EXP_REAL_INDUCTION_V1
      - IDS.EXPERIMENT_IDS.EXP_REAL_INDUCTION_OOD_V1

defaults:
  model_id_key: MODELS.HF_MODEL_GPT2_SMALL
  component_granularity_key: COMPONENT_GRANULARITY.GRANULARITY_DEFAULT
  epsilon_rel_frac_key: DIAGNOSTICS.EPSILON_REL_FRAC
