schema_version_key: SCHEMAS.CONFIG_SCHEMA_VERSION
generators:
  - id: IDS.CANDIDATE_GENERATOR_IDS.G_ACDC
    enabled_key: BOOL.FALSE
  - id: IDS.CANDIDATE_GENERATOR_IDS.G_ATTR_PATCH
    enabled_key: BOOL.TRUE
  - id: IDS.CANDIDATE_GENERATOR_IDS.G_ATPSTAR
    enabled_key: BOOL.FALSE
  - id: IDS.CANDIDATE_GENERATOR_IDS.G_SPARSE_FEATURE
    enabled_key: BOOL.FALSE
  - id: IDS.CANDIDATE_GENERATOR_IDS.G_MANUAL_SEED
    enabled_key: BOOL.TRUE
  - id: IDS.CANDIDATE_GENERATOR_IDS.G_RANDOM_K
    enabled_key: BOOL.TRUE
