schema_version_key: SCHEMAS.CONFIG_SCHEMA_VERSION
log_schema_version_key: SCHEMAS.LOG_SCHEMA_VERSION
required_event_types:
  - ENUMS.LOG_EVENT_TYPES.EVENT_RUN_START
  - ENUMS.LOG_EVENT_TYPES.EVENT_CONFIG_RESOLVED
  - ENUMS.LOG_EVENT_TYPES.EVENT_DATASET_WRITTEN
  - ENUMS.LOG_EVENT_TYPES.EVENT_CANDIDATES_WRITTEN
  - ENUMS.LOG_EVENT_TYPES.EVENT_DIAGNOSTICS_WRITTEN
  - ENUMS.LOG_EVENT_TYPES.EVENT_CERTIFICATE_WRITTEN
  - ENUMS.LOG_EVENT_TYPES.EVENT_REPORT_WRITTEN
  - ENUMS.LOG_EVENT_TYPES.EVENT_RUN_END
